export const TYPES = {
    SET_ORDENES: 'SET_ORDENES',
    SET_SELECTED_ORDEN: 'SET_SELECTED_ORDEN',
    ADD_ORDEN: 'ADD_ORDEN',
    UPDATE_ORDEN: 'UPDATE_ORDEN',
    DELETE_ORDEN: 'DELETE_ORDEN',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
  };

  export const TYPES_AUTH = {
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT: 'LOGOUT',
    LOGIN_ERROR: 'LOGIN_ERROR'
  }